apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-backend
spec:
  defaultBackend:
    service:
      name: mern-backend
      port:
        number: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5001
    name: http
  selector:
    app: mern-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
      version: v1
  template:
    metadata:
      labels:
        app: mern-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: jimsheldon/mernbackend:f5eabe0f
        env:
        - name: MONGO_URI
          value: <+secrets.getValue("mongo_uri")>
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
